// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x92XLbuJrwq6B4TlWcblLWblt/df2lWEpHJ96Ol0xPRxkXRH6SkJAAA4B2lJRu5wHm",
	"EedJpgBwF2XJjp30kjtHBIFv38F8sVwWhIwClcLqfbFCzHEAErj+1yGW2GezkYRg5J1hOVc/eiBcTkJJ",
	"GLV61hUlHyNAxAMqyZQAR1PGkZwDcs3LiEgILNuCTzgIfbB6lgiw7zs36keitgjVxrZFcaCeuvkzLdvi",
	"8DEiHDyrJ3kEtiXcOQTYwColcLXDf73Fzue6c/BuJ/7Defelbncby+T35///n5ZtyUWoz5ec0Jm1XNoF",
	"BKmQmLrwdYgiEm/zQIxTIJ4a8wvgN8SFy0X4AIyFeRnpbfOIrkNR5E97WtSWancRMipAy3Df54C9xfAT",
	"EUbEXUYlUKn+xGHoExcrfHffC4X0lwwZRQ6JiW/18sRCt0TOEfHQs5vAUczyMPeeIWxOQWCOUUSI5aBn",
	"1d3u3mzenTt7cNB19jouONCa7zvQmHX3W/Np+2BfkUpILCNh9dr1A9uSRGqCnoNgEXdh9YAY7/7R+bA/",
	"+M/r4W+ji8sLa5mn5T85TK2e9Y/dTMd3zVOxO+SccUOuItdjeqGYYEvbeoG9c/gYgZAPJN9LAr6HnsVC",
	"cK0gf4aCSEhEmUQTQBCEclEk2t5Bq+1NW+C0J92W024eTJxJfdpxJvteq1MHt9HtQIFo9YxoI3qDfeIh",
	"bqBGOaOW0m108qZ/NBpc989/vToenlw+AuVeYA8lhFra1kvGJ8TzgD6QalcCOPIYCE2lOb4BFAIPiBCE",
	"USQZwq4LQiA5JwLxWE6KRNzH7Q5M21On4+61nU4Lu47bmHYd9wDa3cbUa+51pwUitjIi9s3u0xSLlHRn",
	"w/Pj0cXF6PTkejA8GQ0Hj0C7jFhL23qFRWIIH6qxOcNe0tQ5FqmRfgpFLe8fE+1lf3Q0HFyfnQ8PT08G",
	"o8vR6ckjkO0VFigj1dK2RlRZT+wriwXcvPcwCvYpiih8CsGV4CFQOyHmuhHn4KHbOfEBhZwpGSF0pr1C",
	"rG5FmjZh/4C833/vHMwa+87BHsycWed93Zm1yH69837ebdTf52jaKeqxQUb7G+AGiLwKXw7PT/pHj0DH",
	"9CRDNxQvtK0TJl+yiHqP4DiKYpgqtjboRZodTDrd6awzc7refsfptiee4zVne45Xn3b2mjNo7e/NCnLY",
	"rpBDtfdUg54S7OT08vrl6dXJYyjsCZPIUGZpW1cUR3LOOPkMD6XUG22x1TYq2jAvIJeDDj6wLxDmRsJU",
	"2LCd9eu6zZYHTc9p4U7TaTf3sYO79Y6D97xmu+5N6p22VyBjI2f9ioCk8UpKy6uT/tXlq+HJ5eiwf/ko",
	"JrBAxGW6XzkQ10ESZyFwSYx5xCG5vgEuiKFucdc35gFiU62jebto9kdECvCnaAdqs5qNbhrYD+e48bw2",
	"pqMgiCSe+IDwVAJX7NDkqI1pMeqL37HsfPh281YFaT+raO3dz+bvinjNtvSucC1JAKvgX5IAhMRBiG7n",
	"QFfD7VssDFjgoZ3zl4eo1WodPC9A16w3u0694TRal412r1nv1eu/W7Y1ZTzA0upZHpbg6NNV5Ii9U+ov",
	"krh0BViPiNDHi2sT165EzAK4M+UEqOcvULwWqbWVyUJtTI8TAlMvMwkUjIhPAEU6Bi8T/ELlE2gAN+Cz",
	"MAAq0Ztjy7YC/OkI6EzF8t2WbQWEJv9sVKASVgb9qf1QjxExJDe06iXAOwp4sfulkKotSzAW1+YyoJyI",
	"FNdsF+9vZJEIwd2khDk1uFDLl7YVEe+hSV8NXSorNNVhLhGIRTKMpMOov1CMHVOyTpHQ5RzQaIBcTBW3",
	"mT4X+/4CKSzUiR66IXhMP0bAF1kgi4xx1Jv8P0SmWmxCzm6IB56d5mjA0QwocCxBIIyurkaD2piO6Uvm",
	"++xWoP7wzGk0m6n91KAweqOwZVSUxa7bqcN+u153QIXj7YbXdvBeo+u0291up9Nu1+v1xiYxvHd+t5Hf",
	"Ueh9nf3wsZAoYJ4h9xZWpNNrfI0VWaa/sMl7cJXz/+RgCJ3UjWV5sLB6b61qtbtW/7wm3tJ6Z1uhH3Hs",
	"l9VOeTdCZ5GPeelRZoiTXwNM8Qx4zXODGmG7hcVrSiWP5oqSDX+4pO/tktLU5Yl902N7IydNuYpuKa2n",
	"3eWeci9v9lO5xd/HYSU4PYLjyrj9w4P98GD38mBZBfdtweqX7FEs3e++xuVV6Hbs++Lf73SCTr4Ys8Yb",
	"Ormq/fZuMXtrjX88IqZkWvSRFD7J6xDP4FqyD1DhJy/Vz1pfOUhO4CYpsKg3kXqzNqbDIJQLZBiCCPVU",
	"pgpxOkyEXq6lIl5ekARY/Ovm9+D3z7//9m9y+v7qdvrvX36pcoMcROSbonmpRsw5Xig/XmlMUmXU5TUd",
	"h9zfullZlITVaStClwBnrxB0RdiquXMRm90iahfGasV5v2ICrsbSRh5MCU14U1jDYQocqAtjqpynMasu",
	"o1MyizjOWaaiZJQCuwrJyMImc9BoYDi+jg8xGOI+kVNQJQqRAH59g/0I7hIHtQqZVbG/WQebOXUr4VAR",
	"zBu150aRKNOvCPYGsfibKevX6OjT6ebDdLKkivnu5ENVUa+7i5hVG1XLvOI/dufFtQZiEOpXITkmVAoT",
	"aMMUK9rpvQwUYxoHvgXERJ4o91An3Yw7zMOieBAQOjJvN8q8ta18467aKF3kIVvV+ocbojtrWMsKYUpb",
	"HkUg9c8oaQyjqQ4flcCoWGlvv76Hzjib+BCgga5IG/q/urw8Q/2zkTDCo4PNg5bpDqDzpMtcxYqiNCVV",
	"7jJUr6IAU0cFW5oe8Cn0MTXykeypci1N0Lj3oux6nEDrdojK0/BCiZHEhCY9GCd93YvRkQzNwQ+RB5PI",
	"qAkRYjV727pVu2J/SK4osF0uQjLKFftLxj8cmowiEuCZFzh2PyiWGTWZRLMZobMyAlv2jdOoN+LEScWz",
	"Cq+kPbDCOyUb5iFymQdoJ8DSnYOIe2GxpJkVhUhc96pTAAiVrWZ2MKESZqB7T3EvYsUazhmXNpoXZUdE",
	"QYD5oiAbWh1rY3oxZ5HvKWIqa0OEVFk5djkTebESybsCB6UNChTeprueka/aZhxjd04o5ERfH6foWENX",
	"Sqf6Q01d3S3LPU0yOhoFytGsdPHtlcaMnWt72eVxCbuimW1b58OL06vzw+H18LdX/asLs0tVA9e2+i9O",
	"z83z06vL69OX1+f9k1+HGozR8dnRUAGlH6fNSg3hm/7oqP/iSC0cDPuDo9GJOuxwOBwMB8pH5qi9iuG2",
	"sltyyvGwTizPiXhVOeQKF7ESGMV+apW1A/PAhIGZpmtXVhtT3Qr1IATqCcTigo569kwk1b+duJZg8LAR",
	"jYIJcBtNGPMBUxsZSG2kHZSuCk4ReEQ7lV+m2BdgF2KrKfkEngGotFhnt4W1hBJJsL8rotkMhMy9l1eC",
	"pm3RyPfVHiZF1t08jdS1odb9XPDAvHtKty3oYVdZQh9PwC/RGBGKrka7h0cjgysLiJTgqRiJkxtlSzkL",
	"NKq6phbXWMc6T6/duGFUc1lE5dhC//vf/4PG1hs3jNCh+el52RYcnl2ZZ1tU+BKiF6THcKuE4n/MQc6B",
	"I6CeTimEri7p+sYij6kRMV0WiY2RIkrsu4RBPxUHyKpbRh60Y4Uk4Kpkc6H4EYvf+mLlvy5OTwxR461T",
	"fsgsRLpMYjcU6cEJj2nXmoQOQ3O06FVxJGVTAAHji5ogn+F6NjEPApDYwxLXtFCImiTAx1aJX6UtrY1N",
	"Qm3qNXDXWXsbex4xZb6znE0wxKogyYVR63ykq0Q22VpH7SlPdzyOpxI1682602gqgTvVRUgzRqBcheZ3",
	"QYOVi4vCkHEpMp+RP/oDLG4Z90RPOzQbBYSSIApsFOBP+o8xjYtPNlKuRa8wZNFrkj9Burr6eJ4Y3R6a",
	"SxmK3q6ebXAMiWqMz3Y1GrsxGvmnTkbSInPK4nSizZ5yykrLXMZBoJ2G0+g+N8qmALd6ja7mYfwP2woi",
	"X5LQh9NpnqH5qKJo7UtOQkv2dj4hs1kroB8ymkhIql8qvAtNvpUrNj8TsRbnXAKmTKt/4jIc9FLnQkpp",
	"TUbUQ1jF7+DpuoB4+/pdYr6T07SQ5CayXqf7JJKzcSucpHox2JV7noNgvrKqrk+ASkcQD9AEq5iVUVMP",
	"EeCDuzbRjE/P1Va2167RNGdmsDS2Bz5G2BdK5NFrO6dZz0SKCOaglhePfvv6XW1MDRVQgBeZBxZoJybr",
	"c8VFTReBdgxempTxxrF7WJGdTeaS5fEwyQ4tSETspDjMCKPPaxtDnXj4uETbKrF+Bdg3wBXZUg3yIaaM",
	"Ehf7Bbhz00eZpZ2bjbdp/6xLMPQOKI3XynsvNpIhfvXexfcY9nxFPUVHOS0fpIIwHt3OSurportr6PGy",
	"0hT61zWTi6WROI4sto/VXxOQ5o8/bi857WTds49c77W+ro+cBBCrjDARxXrb9KWiKV1A8zUsHGPmQ0y4",
	"cf8uljBjnHw29Q5TnPMlcJPUv2ByroyYqYrFNWVluGKbVCs7z3i/hdWzKMhbxj8UMtC8w9vSQN3ZfI4F",
	"zlF7id0vhQsOyzG9zKUUbmo1KtqxCbvLQlfcPzc6WpTC4rLHakjfWe879LEQWTm2QgFrY3rIgoDRhG+E",
	"un7kQQ/dBHZSqlIZnRI35Sxt5PqRkMBrY9r3VDijIkXJuPFEplaK3EhIlbooVNEEFowqbwECtmthJG32",
	"7f1rbJ2yYlqxhJuYmcTkKpuS8B1TxEL8UQU2RDt/zNMiXS5J0chk+5uQRIeYSSKAJovC4p6KY94c95CK",
	"4m1kMgEbCck4noGNZioNumbCjgdk1fLDhOI9RAK9Kq3+28kQt41irVEvDGK+9BDQGaFgo9gO597UGxuu",
	"9bLHlHkqTFWYcuaj0MfqbbUvcPFcIXY51zocuTLigG4wJwrJJGLKiZIWP639htCJL1jRfEMD9VecEFm9",
	"fe1XNUm0ABPxQXk2ZSVC7BK50Ks69fSC0oQxmRMa4VnLdyr9ccNIywx350SChtnqWZ/2u9fdtmVbJovq",
	"NZemhJ4XqEaFnbnnqEZBp35MaPyJJjQKTvze0xnNXrvzVNMZBdv+0OmMauen91yZxSisLY5g5B9tjBoL",
	"i0ux45P1bpV3i5uZ92/jnhoHoA9HDvKY0SDMBSBdzqbGDqIA00gp5N2t3+Ht8av6A1u/pZZobMLj3lHS",
	"1TE6nuCLdDtDI6UNwz1ajPmo/nFbxdkswJYZ20pNLhtRSCK6wpWIP05hrqoUF1VYnzfFOnuG31MV24tm",
	"a13ubaBd5eFStwqnLLkmhF2luSsZg/JZg8PjdNrl2BgD1D8bJT5IeZskKCafwUO3eKG4bOzGmBZk3gwI",
	"xOUP6hXa0yYfIXTKcRaY5KrIcVSnjp5mTg3tqB+GdI6pC3rOVXl/JrAvnqdw6a3HNNE4h3ECVCV0Hggy",
	"o3rzf/wDnWdBlQqrfvopp0Hip596aGAiYAlB6GuboyD2yFSXIWUcErPpOiTGFKGdN8drYu/X0QQ4BbVt",
	"HIbb2j7lwu3nBqycqmiwDlUoDF5qXpgCSFeM9C3pYlxbGpZQMGlOZGVhLVs+cYEKLehxbNYPsTsH1KzV",
	"LduKuC5HxFXX29vbGtaPddE1flfsHo0OhycXQ6dZq9fmMvBz7VRrjVgpmU2KDVnKv7QtFgLFIbF6VqtW",
	"r7VN/jXXNmd3zaBh74s1A1mVUWo3o0U3xDNCNfV8IuTaYTqRL26nCbLKCqpnvnT0ZWmoDaFHntWzlIOs",
	"GIETGpnsiw9vv8pDJlf/tbvI7v7nTHr+jtxK0LLaI9Yl7tgiaenWyiqVi5IRpygErmFYc3CAPxl/osxx",
	"4ey0/dSobMVnxfW6ep4vr5fr6atgv9Q8WsPMFb5pdukOh8FJxEjezoGbPlGtNNWGsjEDIiq7ViufmyjR",
	"ZXVMbj1X3pW+ptCs17e44LndTch1E7MVdyMvIp3MTiM/naxQqtmuN9YdkkK9W7xXqV5qbX6pcB+9Y5C+",
	"+42qm9f6FqcZzIiVcI1c6CIUExUm41BXAJXBoHC7dpYyZyNUAOBkmd1oIFR2p5X22brp6WeonPtpj+hB",
	"EDIJ1F1U2RQDWdXo7gajchpnoGVQ1xm0+8h2SZxLmeA9PyXyzkQ2IOQL5i2eUu6T75bkv4qyXFG9xtOD",
	"UO53VHEkKUqLVCn9hVGsx7MNd9zUL04fTZi3QMmoJDKe+dtZhnb9YPMbxS/QPJ49MQq4bj5dL9693x0p",
	"Y358kFA11+ODMUR3DHQXLYR5ZSsLUUWLbMnu+u80VXiodlXjrkqQDapVgvyNhKe9+Y30AxSPJzeGLevl",
	"xt4cvJou4BqLPVkgIsWaSPRXkN9cIOp/DLs5Tfj4F5evX0Fub5QeI1lanyOVulKb8qIf+dA3yYdEBWvu",
	"zoEKLaHNCdDa8LBc/f7eec/fK995UJqzfXbzWHnMo+Qvf+m05TumKxvd7Y/s5A+cnVT4//JnhO6fg2yV",
	"enxVhPngVOPPlmFsJTGFzzM+cVry4GzkHknI04hG/btYv79vjhHP8blVHzLW0xui1I/SDbNSnmJav7pp",
	"fAx8BuhMN8H1zMZe66D7XEcjJ0wCknMsUW62wkwqrQSrmAMidw6aFkXTwPoU0rlNRBAopB1Nxp+fODr4",
	"PvphBnm+c3RggEi/l/rX11Yj1JWxwDwdwK808/EQvDsH94MO5td3b1dM/KtsBP+JJO9VMsm+XDM6iohA",
	"ybR+kSR5xAwlioNSD6uKrJt5qLwhFb9O9EUVZfd0/UJXJsS6Ykl+MOFRiyW1MT2d6NmE3A3F0khQHEZr",
	"sx1yuCEsEml+HM8nfZeCi7lqSJnMRirt7EsOkqFGvb4evm9Sl3nKAKU8iXefgsYW9iX3/fk/Zw0kr5Vb",
	"10DWqPJjl0PiO2SjgTJVayd8b4nvp2O+iFFYX0jJD/89sJAyGlSPQI/pcSRkPISFBicXTqPRbGW3oAMs",
	"0Y7PboG7WADSIzw0CoAT1wwkzRfhHMw9tfzN6OpRZpomD1sUFv8MBZzCWOa3LeCsHF3tLbWs/yELONml",
	"3fgr9H+3Kk7hv3xZjVfKN6C2il/ivL1g6Tbl7Xealw2Z0er/efOt3OJGof975e0lYYqvnCVcNCOeuzgk",
	"u9kc5rvl/wUAAP//BzMDBKtqAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
