// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x96XLbOpb/q6DYXRX7Nilrt61/df3L11Ju1PHWXjJ3bpRRQeSRhIQEGAC0o6T0dR5g",
	"HnGeZAoAd1GW7NjJXfLNEUHw4Ky/s5D5YrksCBkFKoXV+2KFmOMAJHD9r2Mssc9mQwnB0LvAcq5+9EC4",
	"nISSMGr1rBtKPkaAiAdUkikBjqaMIzkH5JqbEZEQWLYFn3AQ+mD1LBFg33du1Y9EbRGqjW2L4kBddfPP",
	"tGyLw8eIcPCsnuQR2JZw5xBgQ6uUwNUO//UWO5/rzuG7nfgP592Xut1tLJPfd///3y3bkotQP19yQmfW",
	"cmkXDkiFxNSFrzsoIvE2jzxxSsRzn/wK+C1x4XoRPuLEwtyM9Lb5g647osg/7XmPtlS7i5BRAVqHj3wO",
	"2FsMPhFhVNxlVAKV6k8chj5xsTrv3nuhDv0lO4xih8TEt3p5ZqE7IueIeOjFbeAoYXmYey8QNk9BYB6j",
	"mBDrQc+qu9392bw7d/bhsOvsd1xwoDU/cKAx6x605tP24YFilZBYRsLqteuHtiWJ1Ay9BMEi7sLqA+Jz",
	"H51cDo76/zke/Dq8ur6ylnle/p3D1OpZf9vLbHzPXBV7A84ZN+wqSj3mF4oZtrStn7F3CR8jEPKR7HtJ",
	"wPfQi1gJxoryFyiIhESUSTQBBEEoF0Wm7R+22t60BU570m057ebhxJnUpx1ncuC1OnVwG90OFJhWz5g2",
	"pLfYJx7ihmqUc2op34Znb45Ohv3x0eUvN6eDs+sn4NzP2EMJo5a29ZLxCfE8oI/k2o0AjjwGQnNpjm8B",
	"hcADIgRhFEmGsOuCEEjOiUA81pMiEw9wuwPT9tTpuPttp9PCruM2pl3HPYR2tzH1mvvdaYGJrYyJR2b3",
	"aXqKlHUXg8vT4dXV8Pxs3B+cDQf9J+Bdxqylbb3CInGEj7XYnGMvWeoci9RJP4ehlvePmfbyaHgy6I8v",
	"LgfH52f94fXw/OwJ2PYKC5SxamlbQ6q8J/aVxwJu7nscB48oiih8CsGV4CFQOyHmuhHn4KG7OfEBhZwp",
	"HSF0pqNCbG5Fnjbh4JC8P3jvHM4aB87hPsycWed93Zm1yEG9837ebdTf53jaKdqxOYyON8ANEXkTvh5c",
	"nh2dPAEf0ycZvqF4oW2dMfmSRdR7gsBRVMPUsLVDL/LscNLpTmedmdP1DjpOtz3xHK8523e8+rSz35xB",
	"62B/VtDDdoUeqr2nmvSUYWfn1+OX5zdnT2GwZ0wiw5mlbd1QHMk54+QzPJZTb7THVtsotGFuQC4HDT6w",
	"LxDmRsMUbNjO+3XdZsuDpue0cKfptJsH2MHdesfB+16zXfcm9U7bK7CxkfN+RUJSvJLy8ubs6Ob61eDs",
	"enh8dP0kLrDAxGW6XxmIa5DEWQhcEuMecUjGt8AFMdwt7vrGXEBsqm007xfN/ohIAf4U7UBtVrPRbQP7",
	"4Rw3dmsjOgyCSOKJDwhPJXAlDs2O2ogWUV98j2Xn4dvtWwXS/qHQ2rt/mL8r8Jpt6V1hLEkAq+RfkwCE",
	"xEGI7uZAV+H2HRaGLPDQzuXLY9RqtQ53C9Q1682uU284jdZ1o91r1nv1+m+WbU0ZD7C0epaHJTj66Qo5",
	"Yu+c+osEl64Q6xER+ngxNrh2BTEL4M6UE6Cev0DxWqTWViYLtRE9TRhMvcwlUDAqPgEUaQxeZviVyidQ",
	"H27BZ2EAVKI3p5ZtBfjTCdCZwvLdlm0FhCb/bFQcJawE/an/UJcRMSw3vOolxDuKeLH3pZCqLUs0Ftfm",
	"MqCcihTXbIf3N4pIhOBuMsKcGVyp5Uvbioj32KSvhq6VF5pqmEsEYpEMI+kw6i+UYEeUrDMkdD0HNOwj",
	"F1Mlbaafi31/gdQp1BM9dEvwiH6MgC8yIIuMc9Sb/D9EplptQs5uiQeeneZowNEMKHAsQSCMbm6G/dqI",
	"juhL5vvsTqCjwYXTaDZT/6lJYfRWnZZRUVa7bqcOB+163QEFx9sNr+3g/UbXabe73U6n3a7X641Navjg",
	"/G6jvKPQ+zr/4WMhUcA8w+4tvEin1/gaL7JMf2GT9+Cq4P/JwRA6aRjL8mBh9d5a1WY3Vv8cE29pvbOt",
	"0I849stmp6IbobPIx7x0KXPEya8BpngGvOa5QY2wvcLiNaWSJwtFyYY/QtL3Dklp6vLMsempo5GTplzF",
	"sJTW0+4LT7mbN8ep3OKnCli5usg42X28ZTyKjcll3FS9PJWN5etzqURHNNFKI3gi1kr+3nCGyHob/JOF",
	"lgdCiUTbngBSZNL4gS1+YIsHYYustv62EI9LkSLW7ndfA0YqvG6MShIvdh88cfJlsjU4xcn1U7YHLNld",
	"a5DLCTHF7CJ6ofBJjkM8g7FkH6ACwVyrn7W9cpCcwG1S+lJ3InVnbUQHQSgXyAgEEeoRV5uIdrhE6OVa",
	"K+LlBU2Axb9ufwt++/zbr/8m5+9v7qb//uc/qwAKBxH5pp1Rqt5zjhcqKFQ6k9QYdeFTI8SHezcrw69Y",
	"PW1F6RLi7BWGrihbtXSuYrdbPNqV8VpxRUYJAVef0kYeTAlNZFNYw2EKHHQ0VKHMuFWX0SmZRRznPFNR",
	"M0qQu0IzMkBrHjTs3xNiMzLEQzBtUKUKkQA+vsV+BPepg1qFzKrN4X9b5VDY8o3ac6NKlPlXJHuDWvzF",
	"jPVrbPT5bPNxNlkyxQIufaQp6nX3MbNqo2qdV/LH7ry41lAMQv0qJMeESmFSIJhixTu9l6FiROOUpHAw",
	"kWfKA8xJt0mP87QoGQSEDs3djbJsi6lDtVO6ylO2avWPd0T3VheXFcqUNqOKROqfUdKyR1MNH5XCKKy0",
	"f1DfRxecTXwIUF/3Cgz/X11fX6Cji6EwyqPB5mHL9G3QZdL/rxJFUZuS/kOZqldRgKmjwJbmB3wKfUyN",
	"fiR7qixYMzTuiim/HmdjulGlMmi8UGokMaFJd8xJb/fi40iG5uCHyINJZMyECLGaV2/dRF/xPyRXrtku",
	"FyEZ54qdPxMfjk1GEYkkl+TY/aBEZsxkEs1mhM7KB9iyo5+i3ogTJ1XPqnMljZsV2SndMBeRyzxAOwGW",
	"7hxE3KWMNc2sKCBxPUWQEkCobDWzBxMqYQa6Kxh3iVa84ZxxaaN5UXdEFASYLwq6oc2xNqJXcxb5nmKm",
	"8jZESKASYZczkVcrkdwrcFDaoMDhbeYeMvZV+4xT7M4JhZzq68cpPtbQjbKpo4Hmru5j5q4mGR2NAhVo",
	"VuYr7JWWmZ1rSNrlQRa7YszAti4HV+c3l8eD8eDXV0c3V2aXqta6bR39fH5prp/fXI/PX44vj85+GWgy",
	"hqcXJwNFlL6ctpE1hW+OhidHP5+ohf3BUf9keKYedjwY9Ad9FSNz3F494ba6WwrK8RhVrM+JelUF5IoQ",
	"sQKM4ji1Ktq+uWBgYGbpOpTVRlQ3qT0IgXoCsbjUpq69EElddieuJZhz2IhGwQS4jSaM+YCpjQylNtIB",
	"Stdrpwg8ooPKP6fYF2AXsNWUfALPEFRarLPbwlpCiSTY3xPRbAZC5u7LG0HTtmjk+2oPkyLrPqs+1Nhw",
	"62EhuG/uPafbllqxqzyhjyfgl3iMCEU3w73jk6E5KwuIlOApjMTJrfKlnAX6qLraGVe/RzpPr926YVRz",
	"WUTlyEL/+9//g0bWGzeM0LH5abfsC44vbsy1LWqvCdML2mOkVTrif8xBzoEjoJ5OKYSuLun6xiJ/UqNi",
	"uiwSO6NcWVKY46fqAFl1y+iDDqyQAK5KMReKH7H6rS8j/+vq/MwwNd46lYfMINJ1gt1QpEdaPKZDawId",
	"BubRolclkVRMAQSML2qCfIbxbGIuBCCxhyWuaaUQNUmAj6ySvEpbWhvbt9rVa+LG2eAB9jxiynwXOZ9g",
	"mFXBkitj1nmkq1Q22Vqj9lSmOx7HU4ma9WbdaTSVwp3rIqQZ8FChQsu7YMEqxEVhyLgUWczIP/oDLO4Y",
	"90RPBzQbBYSSIApsFOBP+o8RjYtPNlKhRa8wbNFrkj9Burr6eJk43R6aSxmK3p6eOnEMi2qMz/b0Mfbi",
	"Y+SvOhlLi8Ipq9OZdnsqKCsrcxkHgXYaTqO7a4xNEW71Gl0tw/gfthVEviShD+fTvEDzqKLo7UtBQmv2",
	"djEh81krpB8zmmhIal8K3oUm38oVm1+I2IpzIQFTps0/CRkOeqlzIWW0JiPqIazwO3i6LiDevn6XuO/k",
	"aVpJcrNyr9N9Es3ZuBVOUr2Y7Mo9L0EwX3lV1ydApSOIB2iCFWZl1NRDBPjgrk0046fnaivbW9dwmnMz",
	"WBrfAx8j7Aul8ui1nbOsFyI9COaglhcf/fb1u9qIGi6gAC+yCCzQTszWXSVFzReBdsy5NCvjjePwsKI7",
	"m9wly5/DJDu0oBFxkOIwI4zu1jZCnXgsvMTbKrV+Bdg3xBXFUk3yMaaMEhf7Bbpzc2GZp52bjbdp/6xL",
	"MPQOKMVr5b0XG9kQ3/rg4ntMe76inh5HBS0fpKIwHqrPSurpovtr6PGy0vsBX9fmL5ZGYhxZbOyrvyYg",
	"zR+/3y5/2sl6YIe/3mt9XYc/ARCrgjCIYr1v+lIxLlA45mtYOMbNh5hwE/5dLGHGOPls6h2mOOdL4Cap",
	"/5nJuXJipioW15SV44p9Uq0cPOP9FlbPoiDvGP9QyEDzAW9LB3XvWECscI7aS+x9Kbx6sox723EgcVOv",
	"UdGOTcRdVrri/rmh3qIWFpc9w6hAhRP0sRBZObbCAGsjesyCgNFEboS6fuRBD90GdlKqUhmdUjcVLG3k",
	"+pGQwGsjeuQpOKOQomTcRCJTK0VuJKRKXdRR0QQWjKpoAQK2a2Ekbfbt42vsnbJiWrGEm7iZxOXu1jK5",
	"Y4pYiD8qYEN08Mc8LdKVZyey/Q0k0RAzSQTQZFFY3FM45s1pDykUbyOTCdhISMbxDGw0U2nQmAk7Hl1W",
	"y48TjvcQCfSqtPpvJ+P1NoqtRt3Qj+XSQ0BnhIKNYj+cu1NvbKTWyy5T5imYqk7KmY9CH6u71b7Axa46",
	"2PVc23DkyogDusWcqEMmiCmnSlr9tPUbRiexYMXyDQ/UX3FCZPUOdFzVLNEKTMQHFdmUlwixS+RCr+rU",
	"01fHJozJnNIIz1q+U+mPG0ZaZ7g7JxI0zVbP+nTQHXfblm2ZLKrXXJoSel6hGhV+5oGjGgWb+jGh8Qea",
	"0CgE8QdPZzR77c5zTWcUfPtjpzOqg188WlaaxSisLY5g5C9tRI2FxSXs+Gy9WxXd4mbmw9u45yYA6Icj",
	"B3nMWBDmApAuZ1PjB1GAaaQM8v7W7+Du9FX9ka3fUks0duFx7yjp6hgbT86LdDtDH0o7hge0GPOo/mlb",
	"xdkswJYZ20pNLhtRSBBd4WWV309hrqoUF1V4nzfFOnt2vucqthfd1rrc21C7KsOlbhVOWfICF3aV5a5k",
	"DCpm9Y9P02mXU+MM0NHFMIlBKtokoJh8Bg/d4YWSsvEbI1rQeTMgEJc/qFdoT5t8hNApxxkwyVWRY1Sn",
	"Hj3NghraUT8M6BxTF/QEsor+TGBf7KZ06a1HNLE4h3ECVCV0HggyM7Osf/sbusxAlYJVP/2UsyDx0089",
	"1DcIWEIQ+trnKIo9MtVlSBlDYjZdd4gRRWjnzeka7P06mgCnoLaNYbit/VMObu8asnKmosk6VlAYvNS9",
	"MEWQrhjp99eLuLY0LKFo0pLIysJat3ziAhVa0WNsdhRidw6oWatbthVxXY6Iq653d3c1rC/romt8r9g7",
	"GR4Pzq4GTrNWr81l4OfaqdYatVI6mxQbspR/aVssBIpDYvWsVq1ea5v8a659zt6aQcPeF2sGsiqj1GFG",
	"q26IZ4Rq7vlEyLXDdCJf3E4TZJUVVM98afRlaaoNo4ee1bNUgKwYgRP6MNm3ON5+VYRMPsqgw0X2VYac",
	"S8+/vbgCWlZ7xLrEHXskrd3aWKUKUTLiFIXANQ1rHhzgTyaeKHdceHbafmpUtuKz4npdXc+X18v19FWy",
	"X2oZrRHmity0uHSHw5xJxIe8mwM3faJaaaoNZWMGRFR2rVY+BFLiy+qY3HqpvCt956JZr2/x6u1276iu",
	"m5iteGv1KtLJ7DTy08kKZZrtemPdQ1Kq94pvvKqbWptvKnwpoGMOff8dVe/E6/drzWBGbIRr9EIXoZio",
	"cBnHugKoHAaFu7WzlDkfoQCAk2V2w75Q2Z022hfrpqdfoHLupyOiB0HIJFB3UeVTDGVVo7sbnMp5nIGW",
	"SV3n0B6i2yV1LmWCD/zIyzuDbEDIn5m3eE69T74ok/9ezXLF9BrPT0K531ElkaQoLVKj9BfGsJ7ON9zz",
	"DYXi9NGEeQuUjEoiE5m/nWdo1w8331H8NtDT+RNjgOvm0/XivYe9vWbcjw8SquZ6fDCO6J6B7qKHMLds",
	"5SGqeJEt2Vv/Ba2KCNWuatxVKbI5apUifyPlaW++I/00yNPpjRHLer2xN4NX0wVc47EnC0SkWINEfwH5",
	"zRWi/vvwm9NEjn9y/foF5PZO6SmSpfU5UqkrtSkv+pEPfZN8SFSI5v4cqNAS2pwArYWH5er39857/lr5",
	"zqPSnO2zm6fKY54kf/lTpy3fMV3ZGG5/ZCe/4+ykIv6XP/D08Bxkq9TjqxDmo1ONP1qGsZXGFD6c+cxp",
	"yaOzkQckIc+jGvXv4v3+ujlGPMfnVn1iWk9viFI/SjfMSnmKaf3qpvEp8BmgC90E1zMb+63D7q5GI2dM",
	"ApJzLFFutsJMKq2AVczhvk/ZrKimofU5tHMbRBCoQzuajf94ZnTwfezDDPJ8Z3RgiEi/ZPvnt1aj1JVY",
	"YJ4O4Fe6+XgI3p2D+0GD+fXd2xUX/yobwX8mzXuVTLIv14yOIiJQMq1fZEn+YIYTxUGpx1VF1s08VL4h",
	"Fd9O9Isqyu/p+oWuTIh1xZL8YMKTFktqI3o+0bMJuTcUSyNBMYzWbjvkcEtYJNL8OJ5P+i4FF/OqIWUy",
	"G6m0sy85SIYa9fp6+r5JXeY5AUp5Eu8hBY0t/Evufwb4Y9ZA8la5dQ1kjSk/dTkkfods2Feuau2E7x3x",
	"/XTMFzEK6wsp+eG/RxZShv3qEegRPY2EjIewUP/symk0mq3sLegAS7TjszvgLhaA9AgPjQLgxDUDSfNF",
	"OAfznlr+zejqUWaaJg9bFBb/CAWcwljmty3grDy6OlpqXf9dFnCyl3bj/x/gr1bFKfxnPKt4pfwG1Fb4",
	"Jc7bC55uU95+r3vZkBmt/m9E3yosblT6v1beXlKm+JWzRIpmxHMPh2Qvm8N8t/y/AAAA///rffZURWwA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
