// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x96XLbOpb/q6DYXZX4Nilrt61/df3LsZQbdby1l0zPjTwqiDySkJAgA4B2lJS+zgPM",
	"I86TTGHhKsqSHTu5t2++ySQAHhyc8zsr6a+WGwZRSIEKbvW+WhFmOAABTP11hAX2w9lQQDD0zrGYy4se",
	"cJeRSJCQWj3rmpJPMSDiARVkSoChaciQmANy9WREBASWbcFnHEQ+WD2LB9j3nVt5kcglIrmwbVEcyLtu",
	"/pmWbTH4FBMGntUTLAbb4u4cAqxpFQKYXOG/3mPnS905uHlpfjg3X+t2t7FMru/8/79atiUWkXq+YITO",
	"rOXSLmyQcoGpC9+2UUTMMo/ccUrEc+/8EtgtceFqET1ix1xPRmrZ/EbXbZHnn/a8W1vK1XkUUg5Khg99",
	"BthbDD4TrkXcDakAKuRPHEU+cbHc7+4HLjf9NduMZIfAxLd6eWahOyLmiHjoxW3gyMPyMPNeIKyfgkA/",
	"RjLByEHPqrvdvdm8O3f24KDr7HVccKA133egMevut+bT9sG+ZBUXWMTc6rXrB7YliFAMvQAexsyF1QeY",
	"fR8eXwwO+/85HvxreHl1aS3zvPwrg6nVs/6ym+n4rr7LdweMhUyzq3jqhl/IMGxpW6+wdwGfYuDikex7",
	"TcD30AsjBGNJ+QsUxFwgGgo0AQRBJBZFpu0dtNretAVOe9JtOe3mwcSZ1KcdZ7LvtTp1cBvdDhSYVs+Y",
	"NqS32CceYppqlAO1lG/D03eHx8P++PDi1+uTwenVE3DuFfZQwqilbb0O2YR4HtBHcu2aA0NeCFxxaY5v",
	"AUXAAsI5CSkSIcKuC5wjMSccMSMnRSbu43YHpu2p03H32k6nhV3HbUy7jnsA7W5j6jX3utMCE1sZEw/1",
	"6tN0FynrzgcXJ8PLy+HZ6bg/OB0O+k/Au4xZS9t6g3kChI/V2BywlzR1jnkK0s+hqOX1DdNeHw6PB/3x",
	"+cXg6Oy0P7wanp0+AdveYI4yVi1ta0glemJfIhYwPe9xHDykKKbwOQJXgIdAroRC140ZAw/dzYkPKGKh",
	"lBFCZ8oqGHUr8rQJ+wfkw/4H52DW2HcO9mDmzDof6s6sRfbrnQ/zbqP+IcfTTlGP9WaUvQGmicir8NXg",
	"4vTw+An4mD5J8w2ZgbZ1GorXYUy9JzAcRTFMFVsBepFnB5NOdzrrzJyut99xuu2J53jN2Z7j1aedveYM",
	"Wvt7s4IctivkUK49VaSnDDs9uxq/Prs+fQqFPQ0F0pxZ2tY1xbGYh4x8gcdy6p1CbLmM9Db0BOQyUM4H",
	"9jnCTEuYdBu2Q7+u22x50PScFu40nXZzHzu4W+84eM9rtuvepN5pewU2NnLoVyQk9VdSXl6fHl5fvRmc",
	"Xg2PDq+eBAILTFym65UdceUksTACJoiGRxyR8S0wTjR3i6u+0zdQOFU6msdFvT4igoM/RS+hNqvZ6LaB",
	"/WiOGzu1ER0GQSzwxAeEpwKYPA7FjtqIFr0+M8ey8+7b7XvppP1Nems3f9O/K/w121KrwliQAFbJvyIB",
	"cIGDCN3Nga6623eYa7LAQy8vXh+hVqt1sFOgrllvdp16w2m0rhrtXrPeq9d/s2xrGrIAC6tneViAo54u",
	"PUfsnVF/kfilK8R6hEc+Xoy1X7viMXNgzpQRoJ6/QGYskmMrg4XaiJ4kDKZeBgkUtIhPAMXKBy8z/FLG",
	"E6gPt+CHUQBUoHcnlm0F+PMx0Jn05bst2woITf5sVGwlqnT6U/yQtxHRLNe86iXEO5J4vvu1EKotSzQW",
	"x+YioJyIFMds5+9vPCIegbtJCXNqcCmHL20rJt5jg74aupIoNFVuLuEojEUUCyek/kIe7IiSdYqEruaA",
	"hn3kYipPO1TPxb6/QHIX8okeuiV4RD/FwBaZI4s0OKpF/h8iUyU2EQtviQeencZowNAMKDAsgCOMrq+H",
	"/dqIjujr0PfDO44OB+dOo9lM8VOREtJbuduQ8rLYdTt12G/X6w5Id7zd8NoO3mt0nXa72+102u16vd7Y",
	"JIYPju82nncced+GHz7mAgWhp9m9BYp0eo1vQZFleiWcfABXGv/PDobISc1YFgdzq/feqla7sfxzTLyl",
	"dWNbkR8z7JfVTlo3Qmexj1npVgbEydUAUzwDVvPcoEbC3cLgNamSJzNFyYI/TdKPNklp6PKHtk1OGoAV",
	"jVSaXbvPWOUmb7ZaucFPBGcJCIwfZo9SCDdsOfexC4r9J0axR/ReK4U4CDRZ5G2HF0ui1urYFuag+QwG",
	"OznFJzDcmbT/tOA/LfiDLHiWwX5fsHolPDbSffMtJr8CzYztN9fvdQKcfDJqjTfg5KoW27sF2aw1/sEx",
	"0Snjoo9A4bMYR3gGYxF+hAo/4UpeVvrKQDACt0mCSc5EcmZtRAdBJBZIHwgi1JOROph0AOFquJIKM7wg",
	"CbD4x+1vwW9ffvvXP8nZh+u76T///nerGopjXxcNSjlyxvBC+jGVYJIqo0ovKj/s4ehmZV4ilk9bEbqE",
	"OHuFoSvCVn06lwZ2i1u71Khl8h7yEHD1Lm3kwZTQ5GwKYxhMgQF1YUSlZdGw6oZ0SmYxwzlkKkpGybGt",
	"kIzMbdQPGvb1ia87B0MGf4jnKK39Bvck5sDGt9iP4T7hkKOQHmWszzpKNQ1biYr0597JNTcKSJmbRbI3",
	"CMmfTHW/RWOfT1Mfp6ElxczXah+rmGrcfcysWqha5uX5Y3deHKspBi6vcsEwoYLrsAOmWPJOraWpGFHj",
	"4RY2xvNMeYA6qdLkUZ4WeQYBoUM9u1E+W9vKlzGrIeoyT9mq1j8TLC0rhCktABWJVJdRUiZHU+VMSoGR",
	"ntPefn0PnbNw4kOA+io/r/n/5urqHB2eD7kWHuV6HrR0rQRdJDX3qqMoSlOS8y9T9SYOMHWk66X4AZ8j",
	"H1MtH8maMvJUDDWVKInyJp2gikMyasULKUYCE5pUpJx0ume2I0I0Bz9CHkxirSaE89VYduvC9Qr+kFyK",
	"ZLvIhGScK1bbtH040vFFzMHTExh2P8oj02oyiWczQmflDWxZRU994JgRJxXPqn0lxZKVs5OyoW8iN/QA",
	"vQywcOfAk+BUS5oeUfDLVeU+JYBQ0WpmDyZUwAxUJc5UZlbQcB4yYaN5UXZ4HASYLQqyodSxNqKX8zD2",
	"PclMiTaECxkkY5eFPC9WPJnLcVBaoMDhbXoNMvZVY8YJdueEQk701eMkH2voWurU4UBxV9UOc3eT+I7G",
	"gTQ0Kz0N9kqZys4VAe1y84hdUdq3rYvB5dn1xdFgPPjXm8PrS71KVTnbtg5fnV3o+2fXV+Oz1+OLw9Nf",
	"B4qM4cn58UASpW6npVtF4bvD4fHhq2M5sD847B8PT+XDjgaD/qAvbWSO26s73FZ2S0bZtC4ZeU7Eq8og",
	"V5iIFcfI2KnVo+3rG9oNzDRdmbLaiKrCsAcRUI+j0CS05L0XPMmFvjSZBb0PG9E4mACz0SQMfcDURppS",
	"GykDpXKkUwQeUUbl71Psc7ALvtWUfAZPE1QarGLdwlhCiSDY3+XxbAZc5ObllaBpWzT2fbmGDphVbVNt",
	"aqy59TAT3Ndzz+i26U3sSiT08QT8Eo8Roeh6uHt0PNR7DQMiBHjSR2LkVmIpCwO1VZVTNBnnkYraa7du",
	"FNfcMKZiZKH//e//QSPrnRvF6Ehf2iljwdH5tb63mkJZQYKE6QXp0adV2uJ/zEHMgSGgngopuMo1qWzH",
	"Ir9TLWIqSWLASDLF2C6ut5+KA2S5Li0PyrBC4nBVHnMhFWLEb32y9h+XZ6eaqWbp9DxE5iJdJb4bilUb",
	"iRcq05q4DgP9aN6rOpH0mAIIQraocfIFxrOJvhGAwB4WuKaEgtcEATaySudVWnJz3KegXhE3zor92POI",
	"Tvqd5zBBM6uCJZdarfOerhTZZGnltadn+tJjeCpQs96sO42mFLgzlZLUTRXSVKjzLmiwNHFxFIVM8Mxm",
	"5B/9ERZ3IfN4Txk0GwWEkiAObBTgz+rHiJpUlI2kaVEjNFvUmOQnCFflIi8S0O2huRAR7+2qTg9Hs6gW",
	"stmu2sau2Ub+rpOxtHg4ZXE6VbAnjbLUMjdkwNHLhtPo7mhlk4RbvUZXnaH5w7aC2Bck8uFsmj/QvFdR",
	"RPuSkVCSvZ1NyDBrhfSjkCYSkuqXdO8iHW/lUs8vuNHinEnANFTqn5gMB71WsZBUWh0R9RCW/jt4Ki/A",
	"37+9SeA7eZoSklx/2tt0nURyNi6Fk1DPkF255gXw0Jeo6voEqHA48QBNsPRZQ6rzIRx8cNcGmubpudxK",
	"tXZ9TaO75WqAVnauIg3yhtY8WL40SYiPsEBvdyRQJbtbsdTDaQ7EsNDIBp9i7HM93c6Nf8HThTADOby4",
	"sfdvbxLjTzgKcPReE3Lz/gbTRU8uqGfqy9xO0khqNblP5Z5iutAWKxmnxEoJKTfGaUVyN4F1mN+nDrVo",
	"QR6NiWQwIyHdqW10tEwjeOlkq5TqDWBfE1cUimqSjzANKXGxX6A71wmW4fxcL7xNKWpdeKNWQKm3WF57",
	"sZENZuqDCwGG9nx2P92ONJk+CEmhaaPP0vvpoPvz+WZY6Y2AbyvsFxMzxostlvLlrwkI/eP3W9dPq2oP",
	"rOnXe61vq+kn7svqQWh/5j5kXG0QKGzzLSwcjX4RJkwjnYsFzEJGvuhsi04N+gKYTim8CsXcYBL18lBk",
	"YKdWNt1mvYXVsyiIu5B9LMS/eXO7JUDdW/o3AufItfju18LLJktT9jZmzE1R454aelnoiuvn2niLUlgc",
	"9lTdbPdmG498zHmWDK5QwNqIHoVBENLk3Ah1/diDHroN7CRRJuNJKW7SVNvI9WMuVMPAoSedKemnipBJ",
	"Q7UwmVrkxlzIwEluFU1gEVJpLYBDZd5ybcl/e9/ZoFOWyismkBOYSSB3p5adO6YojPAn6VYR5XpglqYI",
	"cyGS2ky2vnaIlIObhCFosigM7kkv6t1JD8kYwkY6DrERFyHDM7DRTAZh45DbpllZDj9KON5DJFCj0tqD",
	"nTTU28hojZzQN+fSQ0BnhIKNDA7nZqqF9an1sts09KSTLHfKQh9FPpaz5brA+I7c2NVc6XDsipgBusWM",
	"yE0m/lpOlJT46S4RxejEFqxovuaB/GXCMau3r+yqYokSYMI/SssmUSLCLhELNapTT18Wm4ShyAkN96zl",
	"jQy+3ChWMsPcORGgaLZ61uf97rjbtmxLx3C95lIn8PMC1ajAmQe2jRR06me3yB+oW6RgxB/cKdLstTvP",
	"1SlSwPbHdopUGz+15kpfSGFssR0kf2uj11gYXPIdn61yLK2bKaU+vIh8pg2AejhykBdqDcKMA1LJdKpx",
	"EAWYxlIh7y88D+5O3tQfWXguFWQNhJvKVVJT0jqe7BepYoralAKGBxQ481790xaqs06ELSO2lYxg1iCR",
	"eHSF11N+P2nBqkRgXIE+74pZ/mx/z5XqL8LWuthbU7t6hktVqJyGyStb2BU6o7Ja0u4fnaSdN6ahFB2e",
	"DxMbJK1N4hSTL+ChO7yQp6xxY0QLMq/bE0x6hHqF4riORwidMpw5JrkctvHq5KOnmVFDL+WFAZ1jappe",
	"pfUPOfb5TkqXWnpEE41zQkaAyoDOA05mVC3+l7+gi8ypkm7VL7/kNIj/8ksP9bUHLCCIfIU5kmKPTFUS",
	"VBiXOJyu28SIIvTy3cka3/ttPAFGQS5r3HBb4VPO3d7RZOVURZF1JF1h8FJ4CSVBKimk3lgv+rWlVg1J",
	"kzqJLCmtZMsnLlCuBN34ZocRdueAmrW6ZVsxU+kIk/O9u7urYXVbpXzNXL57PDwanF4OnGatXpuLwM8V",
	"c601YiVlNkk2ZCH/0rbCCCiOiNWzWrV6ra3jr7nCnN01TY+9r9YMRFVEqcyMEt0IzwhV3PMJF2sb+3g+",
	"tZ4GyDIqqO4/U96XpajWjB56Vs+SBrKiHY+rzWRf33j/TRYy+QyDMhfZdxhykJ5/X3HFaVmtUKsEu0Ek",
	"Jd1KWYU0USJmFEXAFA1rHhzgz9qeSDguPDstfjUqGwGy1H5d3s8n98vZ/FWyX6szWnOYK+emjkvVV/Se",
	"uNnk3RyYrlLVSj11KGtyILyyZrby6Y8SX1ab9Nafyk3pyxbNen2Ll223eyt1XfduxXuql7EKZqexn/Z1",
	"SNVs1xvrHpJSvVt8x1VOam2eVPg2QEdv+v4ZVW/BqzdqdVuIUcI1cqGSUCGvgIwjlQGUgEHhbm0nZw4j",
	"pAPgZJHdsM9ldKeU9sW6Tu4XqBz7KYvoQRCFAqi7qMIUTVlVG/EGUDkzEWiZ1HWA9hDZLolzKRJ84Gdd",
	"brRnA1y8Cr3Fc8p98g2Z/Bdqliuq13h+Esr1jqoTSZLSPFVKf6EV6+mw4Z6vJhR7nyaht0BJoybSlvn7",
	"IUO7frB5RvFrQE+HJ1oB1/XKq8G7D3tDTcOPDwKquop80EB0Tzt5ESH0lK0QoooX2ZDd9d/MqrBQ7arC",
	"XZUg661WCfJ3Ep725hnpx0CeTm70sayXG3uz86qrgGsQe7JARPA1nuivIL67QNR/H7g5Tc7x31y+fgWx",
	"PSg9RbC0PkYqVaU2xUU/46HvEg/xiqO5PwYqlIQ2B0Br3cNy9vtHxz1/rnjnUWHO9tHNU8UxTxK//FuH",
	"LT8wXNlobn9GJ7/j6KTC/pc/6fTwGGSr0OObPMxHhxp/tAhjK4kpfCrzmcOSR0cjDwhCnkc06j8E/f68",
	"MYbp43OrPiqtujd4qR6l25mLUqNLv6pofAJsBuhcFcFVz8Ze66C7o7yR01AAEnMsUK63QncqrTirmAEi",
	"9zaaFkVT0/oc0rmNRxDITTuKjX97Zu/gx+iHbuT5wd6BJiL9du2/v7Zqoa70BeZpA34lzJsmeHcO7kfl",
	"zK+v3q5A/JusBf+ZJO9N0sm+XNM6ighHSbd+kSX5jWlOFBulHpcVWdfzUPl+lplO1GsyEvdU/kJlJvi6",
	"ZEm+MeFJkyW1ET2bqN6E3PuRpZYg40Yr2I4Y3JIw5ml8bPqTfkjCRb+rQ0ORtVTa2XckRIga9fp6+r5L",
	"XuY5HZRyJ95DEhpb4EvufwH8MXMgea3cOgeyRpWfOh1i3jEb9iVUre3wvSO+n7b5opDC+kRKvvnvkYmU",
	"Yb+6BXpET2IuTBMW6p9eOo1Gs5W9gx1ggV764R0wF3NAqoWHxgEw4uqGpPkimgPlO6X3sqtbmWkaPGyR",
	"WPwjJHAKbZnfN4Gz8uhqa6lk/XeZwMleGTb/EeDPlsUp/PudVX+l/AbUVv6LidsLSLcpbr8XXjZERqv/",
	"f+h7mcWNQv/nittLwmReOUtOUbd47uKI7GZ9mDfL/wsAAP//2Yv+ajdsAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
